name: Add bug pull requests needing review to projects

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project
        with:
          project-url: https://github.com/orgs/caffeinesoftware/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: needs-review, bug
          label-operator: AND